name: Update Blog JSON data

on:
  workflow_dispatch:
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "0 22 * * *"
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # clone private repo
      - name: Clone private repo
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          owner: 'tianheg'
          repository: 'blog'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Access cloned repository content
        run: |
          cd blog
          ls -l

      # gen json
      # - name: Use Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 16
      # - run: npm install
      # - run: node gen-json.js
      # - name: Commit files
      #   run: |
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git commit -m "Update json files" -a || true
      #     # The above command will fail if no changes were present, so we ignore
      #     # the return code.
      # - name: Push changes
      #   uses: tianheg/github-actions@push
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
